"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-20
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


# Each CREATE is a separate statement so it works in both online and offline (--sql) modes.
UPGRADE = [
    # --- Catalogs (materialized; idempotent daily upserts) ---
    """
    CREATE TABLE openrouter_models (
        slug TEXT PRIMARY KEY,
        name TEXT,
        modality TEXT,
        context_length INTEGER,
        price_prompt NUMERIC,
        price_completion NUMERIC,
        raw JSONB,
        first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_seen TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX ix_openrouter_first_seen ON openrouter_models (first_seen)",
    "CREATE INDEX ix_openrouter_last_seen ON openrouter_models (last_seen)",
    """
    CREATE TABLE foundry_models (
        model_id TEXT PRIMARY KEY,
        normalized_name TEXT,
        publisher TEXT,
        version TEXT,
        deployment_options JSONB,
        retirement_date DATE,
        raw JSONB,
        first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_synced TIMESTAMPTZ
    )
    """,
    "CREATE INDEX ix_foundry_normalized_name ON foundry_models (normalized_name)",
    # --- Queue + decisions ledger ---
    """
    CREATE TABLE candidates (
        slug TEXT PRIMARY KEY,
        source TEXT NOT NULL CHECK (source IN ('openrouter','teams')),
        status TEXT NOT NULL CHECK (status IN
            ('discovered','pending','queued','running','done','rejected','deferred')),
        foundry_available BOOLEAN,
        foundry_model_id TEXT,
        decided_at TIMESTAMPTZ,
        decided_by TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX ix_candidates_status ON candidates (status)",
    """
    CREATE TABLE model_aliases (
        canonical_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        openrouter_slug TEXT,
        foundry_model_id TEXT,
        native_provider TEXT,
        native_model_id TEXT
    )
    """,
    "CREATE UNIQUE INDEX ux_model_aliases_or ON model_aliases (openrouter_slug)",
    # --- Admin-set per-use-case config (baseline model, reps, temperature) ---
    """
    CREATE TABLE use_case_config (
        use_case TEXT PRIMARY KEY,
        baseline_model TEXT,
        n_reps INTEGER NOT NULL DEFAULT 3,
        temperature DOUBLE PRECISION,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    # --- Benchmarks (parent) → runs (per rep) → results / scores ---
    """
    CREATE TABLE benchmarks (
        benchmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug TEXT NOT NULL,
        use_case TEXT NOT NULL,
        route TEXT,
        provider TEXT,
        judge_model TEXT,
        judge_version TEXT,
        n_reps INTEGER NOT NULL,
        is_baseline BOOLEAN NOT NULL DEFAULT false,
        started_at TIMESTAMPTZ,
        finished_at TIMESTAMPTZ,
        status TEXT NOT NULL DEFAULT 'running'
    )
    """,
    "CREATE INDEX ix_benchmarks_usecase_slug ON benchmarks (use_case, slug)",
    """
    CREATE TABLE runs (
        run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        benchmark_id BIGINT NOT NULL REFERENCES benchmarks(benchmark_id) ON DELETE CASCADE,
        rep_index INTEGER NOT NULL,
        started_at TIMESTAMPTZ,
        finished_at TIMESTAMPTZ,
        status TEXT NOT NULL DEFAULT 'running',
        transcript JSONB,
        UNIQUE (benchmark_id, rep_index)
    )
    """,
    """
    CREATE TABLE results (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id BIGINT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
        use_case TEXT NOT NULL,
        input_id TEXT NOT NULL,
        raw_output TEXT,
        latency_ms DOUBLE PRECISION,
        tokens_in INTEGER,
        tokens_out INTEGER,
        cost NUMERIC,
        call_breakdown JSONB,
        UNIQUE (run_id, input_id)
    )
    """,
    """
    CREATE TABLE item_scores (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id BIGINT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
        input_id TEXT NOT NULL,
        use_case TEXT NOT NULL,
        metric TEXT NOT NULL,
        mode TEXT NOT NULL CHECK (mode IN ('deterministic','semantic')),
        value DOUBLE PRECISION NOT NULL,
        rationale TEXT,
        UNIQUE (run_id, input_id, metric)
    )
    """,
    """
    CREATE TABLE scores_per_run (
        run_id BIGINT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
        use_case TEXT NOT NULL,
        metric TEXT NOT NULL,
        value DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (run_id, metric)
    )
    """,
    """
    CREATE TABLE scores (
        benchmark_id BIGINT NOT NULL REFERENCES benchmarks(benchmark_id) ON DELETE CASCADE,
        use_case TEXT NOT NULL,
        metric TEXT NOT NULL,
        mean DOUBLE PRECISION NOT NULL,
        min DOUBLE PRECISION NOT NULL,
        max DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (benchmark_id, metric)
    )
    """,
    """
    CREATE TABLE baselines (
        use_case TEXT NOT NULL,
        metric TEXT NOT NULL,
        mean DOUBLE PRECISION NOT NULL,
        min DOUBLE PRECISION NOT NULL,
        max DOUBLE PRECISION NOT NULL,
        model TEXT,
        benchmark_id BIGINT REFERENCES benchmarks(benchmark_id) ON DELETE SET NULL,
        judge_model TEXT,
        judge_version TEXT,
        set_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (use_case, metric)
    )
    """,
    # --- Observability + Teams inbound poll table ---
    """
    CREATE TABLE run_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        benchmark_id BIGINT,
        run_id BIGINT,
        ts TIMESTAMPTZ NOT NULL DEFAULT now(),
        level TEXT,
        event TEXT,
        detail JSONB
    )
    """,
    "CREATE INDEX ix_run_logs_corr ON run_logs (benchmark_id, run_id)",
    """
    CREATE TABLE teams_inbox (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind TEXT NOT NULL,
        payload JSONB NOT NULL,
        received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        processed_at TIMESTAMPTZ
    )
    """,
    "CREATE INDEX ix_teams_inbox_unprocessed ON teams_inbox (processed_at) WHERE processed_at IS NULL",
]

DOWNGRADE = [
    "DROP TABLE IF EXISTS teams_inbox",
    "DROP TABLE IF EXISTS run_logs",
    "DROP TABLE IF EXISTS baselines",
    "DROP TABLE IF EXISTS scores",
    "DROP TABLE IF EXISTS scores_per_run",
    "DROP TABLE IF EXISTS item_scores",
    "DROP TABLE IF EXISTS results",
    "DROP TABLE IF EXISTS runs",
    "DROP TABLE IF EXISTS benchmarks",
    "DROP TABLE IF EXISTS use_case_config",
    "DROP TABLE IF EXISTS model_aliases",
    "DROP TABLE IF EXISTS candidates",
    "DROP TABLE IF EXISTS foundry_models",
    "DROP TABLE IF EXISTS openrouter_models",
]


def upgrade() -> None:
    for stmt in UPGRADE:
        op.execute(stmt)


def downgrade() -> None:
    for stmt in DOWNGRADE:
        op.execute(stmt)
